users:
    schema:
        timestamps: true
        fields:
            fullname:
                type: String
            username:
                type: String
                required: true
            role:
                type: String
                required: true
                enum: "'user', 'admin'"
                default: 'user'
            password:
                type: String
                required: true
    permissions:
        default:
            enabled: true

comments:
    schema:
        timestamps: true
        fields:
            content:
                type: String
                required: true
            author:
                type: objectid
                required: true
                ref: users
            post:
                type: objectid
                required: true
                ref: posts
    permissions:
        default:
            enabled: true
            fieldsPopulate:
                - path: author
                  select: fullname
                - path: post
                  select: title

posts:
    schema:
        timestamps: true
        fields:
            title:
                type: String
                required: true
            content:
                type: String
                required: true
            _cid:
                type: String
                required: true
                auto:
                    prefix: 'POST'
                    length: 6
            author:
                type: objectid
                required: true
                ref: users
                fromUser: _id
    permissions:
        default:
            enabled: true
        updateById:
            default:
                fieldsFilter:
                    denied:
                        - title
